### ISSUE TITLE
Image caption support in Plone 5.1.x   Add Upgrade step for Plone 5.1.x

### ISSUE THREAD

**Issue by tuticapi** [plone/plone.app.upgrade#231]
Enable the image caption on TinyMCE. The plone-logged-in-compided.js file was re compiled.
The upgradeStep update filed last_compilation.

ref:
https://github.com/plone/plone.outputfilters/issues/37
https://github.com/plone/mockup/issues/977
https://github.com/plone/Products.CMFPlone/issues/3098

**Comment by vincentfretin** [comment]
Image caption feature is available in Plone 5.2.2.
