### ISSUE TITLE
plone.api dependency has slipped in [5.2]

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.upgrade#241]
In `move_dotted_to_named_behaviors` I see `from plone import api`. This is not allowed in core code.
I noticed this when looking at something else.

**Comment by mauritsvanrees** [comment]
Well, I guess it is not so bad, because it is only imported inside a function, so it will not lead to circular imports or similar.
Still, should be fixed.

**Comment by gforcada** [comment]
But, at the same time, having a nice clean API that does regular tasks more pleasant to use, would make core code more readable/approachable.

Wouldn't be wise (though with more effort) to make `plone.api` **not** depend on core packages, but contain the code in itself rather than being a thin layer? :thinking:

**Comment by gforcada** [comment]
After a 2 minutes quick look at the top level imports on the handful of plone.api modules, there are less than 10 (maybe even 5) imports to the plone namespace or Products.CMFPlone...

Food for thought...

**Comment by mauritsvanrees** [comment]
Then the code would be in core Plone **and** in `plone.api`. So any fix would need to be done in two places.
Also, currently `plone.api` is compatible with Plone 4.3-5.2. You can't do that when you have duplicated the code.

Anyway, I will remove the use here.

Grepping in coredev 5.2 Python 3 `parts/packages` I am glad that I don't see much use of it:
```
$ ack 'from plone import api'
Products/CMFPlone/tests/test_login_help.py
2:from plone import api

plone/app/upgrade/v52/final.py
42:    from plone import api

plone/app/multilingual/tests/test_uninstall.py
1:from plone import api

plone/app/discussion/browser/moderation.py
6:from plone import api

plone/restapi/deserializer/blocks.py
4:from plone import api
```

There are *lots* more matches in `plone.restapi` tests, but I guess that is okay.
(I obviously skipped matches in `plone.api` itself.)
