### ISSUE TITLE
Some bundles are missing after upgrade to Plone 6 with ES6

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.upgrade#275]
Compared to a fresh site, a migrated site is missing the `jquery`, `plone-logged-in` and `plone-legacy` bundles. On a new site, the last one is created by `plone.app.event`. It is maybe no longer needed.

Result is that lots of javascript is not working. See comments in this PR: https://github.com/plone/plone.app.upgrade/pull/269

I assign Johannes, but feel free to pass it to someone else. Or someone else can volunteer.

**Comment by pbauer** [comment]
https://github.com/plone/plone.app.upgrade/pull/277 should add jquery and remove plone-logged-in together with the commits from https://github.com/plone/Products.CMFPlone/issues/3467. 

plone-legacy should be gone once https://github.com/plone/Products.CMFPlone/issues/3469 is solved.
