### ISSUE TITLE
Upgrade Plone 5.2.10 to 6.0.0b3 does not keep site root's blocks and blocks_layout

### ISSUE THREAD

**Issue by erral** [plone/plone.app.upgrade#304]
I don't know if this is the right place to discuss this or the place should be plone.volto

We have a Plone 5.2.10 site as a backend for a Volto 16 app.

I have migrated Plone to 6.0.0b3 and I have seen that although the Plone site has been migrated into a Dexterity object, and although the old root having the `blocks` and `blocks_layout` properties so that a Volto page can be configured in the root of the site, the migration step did not take this into account.

IMHO the migration code should have taken into account that the site was been used as a Volto site (the `blocks` and `blocks_layout` properties on the root of the site signal them), and if so enable the `Blocks` layout on the Plone Site and migrated the content of the said properties to the proper behavior-provided fields.

Opinions @pbauer @mauritsvanrees @jensens ?

**Comment by mauritsvanrees** [comment]
This should be fixed. Probably in plone.app.upgrade. Although? I don't immediately see where in the [main upgrade step](https://github.com/plone/plone.app.upgrade/blob/3.0.0b5/plone/app/upgrade/v60/alphas.py#L80) this information would get lost. You could add a pdb in that function and try to see where it breaks: before, during or after this function.

Maybe it is still fine after plone.app.upgrade is done, but an upgrade step in `plone.volto` resets the values. Just a guess.

**Comment by erral** [comment]
> This should be fixed. Probably in plone.app.upgrade. Although? I don't immediately see where in the [main upgrade step](https://github.com/plone/plone.app.upgrade/blob/3.0.0b5/plone/app/upgrade/v60/alphas.py#L80) this information would get lost. You could add a pdb in that function and try to see where it breaks: before, during or after this function.
> 
> Maybe it is still fine after plone.app.upgrade is done, but an upgrade step in `plone.volto` resets the values. Just a guess.

I think that the point is that that upgrade code never sets the `volto.blocks` behavior to the Plone Site object after migrating it to dexterity.

I would say that, after migratint the site root to DX, we need to check if the original site was being used as a Volto site (checking if it has the `blocks` and `blocks_layout` properties set, and if so enable the `volto.blocks` behavior.

**Comment by mauritsvanrees** [comment]
That sounds about right.
