### ISSUE TITLE
problem with plone.base.interfaces.syndication.ISiteSyndicationSettings when upgrading from 5.x to 6

### ISSUE THREAD

**Issue by luca-bellenghi** [plone/plone.app.upgrade#315]
While upgrading some Plone sites (5.2.6 and 5.2.7), I encountered an issue with the ISiteSyndicationSettings interface on all of them. 

The problem seems to arise from the fact that the interface is still located inside Products.CMFPlone but points to plone.base.interfaces.syndication. 

Therefore, attempting to access the Syndication control panel results in the error message: 

"KeyError: 'Interface plone.base.interfaces.syndication.ISiteSyndicationSettings defines a field allowed, for which there is no record.'"

I also tried installing a vanilla Plone 5.2.7 and upgrading it to Plone 6.0.3; I still get the same error. 
I'm using plone.app.upgrade 3.0.3

**Comment by 1letter** [comment]
looks like the same https://github.com/plone/Products.CMFPlone/issues/3805

**Comment by petschki** [comment]
I just got the same error for a migrated Site (5.2 -> 6.0.4) when trying to update to 6.0.7rc1 ... all `ISiteSyndicationSettings` keys are still from `CMFPlone` and when trying to run upgrade step `6018` the following traceback occurs:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 390, in publish_module
  Module ZPublisher.WSGIPublisher, line 285, in publish
  Module ZPublisher.mapply, line 98, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Products.GenericSetup.tool, line 1129, in manage_doUpgrades
  Module Products.GenericSetup.upgrade, line 193, in doStep
  Module plone.app.upgrade.v60.final, line 192, in fix_syndication_settings
  Module plone.registry.registry, line 45, in __setitem__
  Module plone.registry.registry, line 187, in __getitem__
  Module plone.registry.registry, line 244, in _getField
KeyError: 'plone.base.interfaces.syndication.ISiteSyndicationSettings.allowed'
```

The upgrade step wants to set the new key from `plone.base.interfaces.syndication.ISiteSyndicationSettings` but they do not exist at that time. In fact, the profile `Products.CMFPlone:plone` still loads the registry entries from the old interace:

https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/profiles/dependencies/registry.xml#L106

This needs to be changed too.

/cc @mauritsvanrees
