### ISSUE TITLE
Implement an upgrade step for Plone 6.1

### ISSUE THREAD

**Issue by 1letter** [plone/plone.app.upgrade#324]
some registry entries should be upgraded via upgrade step if a site is upgraded to Plone 6.1. the interfaces `ITinyMCEPluginSchema` and `IFilterSchema` contains  new values.

**Comment by 1letter** [comment]
It should be implemented in Plone 6.0 also.

**Comment by jensens** [comment]
> It should be implemented in Plone 6.0 also.

@mauritsvanrees What do you think? I tend to not change much feature wise in 6.0.x

**Comment by 1letter** [comment]
@jensens https://github.com/plone/Products.CMFPlone/issues/3935#issuecomment-2073598467

**Comment by mauritsvanrees** [comment]
All merged now AFAIS.
