### ISSUE TITLE
Huge performance issue with to501

### ISSUE THREAD

**Issue by Gagaro** [plone/plone.app.upgrade#60]
This part of the upgrade is basically waking up and reindexing all of the dexterity object of the catalog: https://github.com/plone/plone.app.upgrade/blob/master/plone/app/upgrade/v50/final.py#L53-L55

```python
iface = "plone.dexterity.interfaces.IDexterityContent"
for brain in search(object_provides=iface):
    brain._unrestrictedGetObject().reindexObject(idxs=['getIcon'])
```

It is just not feasible on a huge site. If this is for a `getIcon` index, this should be done for the whole catalog using `reindexIndex`. But I'm guessing this is for the `getIcon` metadata (there is no `getIcon` index?), so I'm not sure what the right method should be (or if there is even one)?

**Comment by Gagaro** [comment]
see https://github.com/plone/plone.app.upgrade/pull/61

**Comment by Gagaro** [comment]
The fix is actually not good. The indexer method will not be called and the metadata will be the value off the objects attributes directly.

**Comment by Gagaro** [comment]
@jensens

**Comment by Gagaro** [comment]
Ok I might have found a way to update only this metadata correctly, I'll do a PR.

**Comment by jensens** [comment]
PR was merged long time ago, close issue.
